### ISSUE TITLE
Geeting error that typings does not exist

### ISSUE THREAD

**Issue by shafaqat309** [BenedicteGiraud/react-sliding-side-panel#18]
I am trying to install the typings for the latest project but I am getting error that typings does not exist
"@types/react-sliding-side-panel": "^1.0.14",

Do you have typings for the module? If yes, can you tell me the package number, if no, can you provide that?

**Comment by BenedicteGiraud** [comment]
Hello @shafaqat309,
The module is now written in typescript, you can find an example here https://github.com/BenedicteGiraud/react-sliding-side-panel/blob/master/examples/example2-typescript/src/example.tsx
