### ISSUE TITLE
does not work with nextjs.

### ISSUE THREAD

**Issue by a-eid** [BenedicteGiraud/react-sliding-side-panel#22]
the way this library uses css, is not supported by nextjs, 

it's probably better to have the user auto import the library css manually ...

**Comment by BenedicteGiraud** [comment]
Hello @a-eid,
The version 2.0.3 is working with nextjs as need to include the css file yourself. 
You have an example here: https://github.com/BenedicteGiraud/react-sliding-side-panel/tree/master/examples/example3-nextjs
