### ISSUE TITLE
Add custom class to panel-content div

### ISSUE THREAD

**Issue by kevbarns** [BenedicteGiraud/react-sliding-side-panel#7]
Hello,

Super cool panel, I got what I wanted with it. would it be possible to add a prop to add custom classes to the main div with the class panel-content ?

In any case, thanks !

**Comment by BenedicteGiraud** [comment]
Hi @kevbarns !

Thanks for your feedback !
I added the possibility to add custom classes to the panel-content, you can see the changes in the PR #9.
You can install the version 1.0.8 of the package to have the changes.

Thanks again !

**Comment by kevbarns** [comment]
Hello @BenedicteGiraud,

That is so cool ! Thank you for this update !!
I'm updating the package tomorrow and let you know 👍 

Kevin
